insert into bills(
  id, 
  "customerID",
  "generatedOn",
  "dueDate",
  recurrence,
  "billType",
  "billerBillID",
  "platformBillID",
  "billerCategory",
  "billerProductInstanceID",
  "amountExactness",
  "validationRules",
  "billFetchStatus",
  "currencyCode",
  amount,
  "paymentDetails",
  discounts,
  fees,
  items,
  taxes,
  "createdAt",
  "updatedAt"
) values (
  '9e3d2206-076a-466f-9b55-bff2d4d8d9d3',
  '753e286d-b593-4f09-bbe1-e0eea965fb5d',
  NOW(),
  NOW() + INTERVAL '30 DAYS',
  'ONE_TIME',
  'COLLECT',
  '12123131322',
  '',
  '',
  '',
  'EXACT',
  '{ "amount": { "maximum": 23413, "minimum": 234 } }',
  'AVAILABLE',
  'INR',
  '{"currency": "INR", "value": 15000}',
  '{}',
  '{}',
  ARRAY['{}']::JSONB[],
  ARRAY['{}']::JSONB[],
  ARRAY['{}']::JSONB[],
  now(),
  now()
);