module.exports.constants = {
  UNAUTHENTICATED_USER_HEADER: 'notSignedIn',
  USER_UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_AUTHENTICATED: 'AUTHENTICATED',
  USER_ADMIN: 'ADMIN',
  ACCESS_TOKEN_NOTFOUND: 'ACCESS_TOKEN_NOTFOUND',
  FORBIDDEN: 'FORBIDDEN',

  ENUM_RECURRENCE: [
    'ONE_TIME',
    'DAILY',
    'WEEKLY',
    'FORTNIGHTLY',
    'MONTHLY',
    'QUARTERLY',
    'HALF_YEARLY',
    'YEARLY',
    'AS_PRESENTED'
  ],

  ENUM_BILL_TYPE: ['GST', 'COLLECT'],

  ENUM_AMOUNT_EXACTNESS: [
    'ANY',
    'EXACT',
    'EXACT_UP',
    'EXACT_DOWN',
    'RANGE'
  ],

  ENUM_BILL_FETCH_STATUS: ['AVAILABLE', 'NO_OUTSTANDING', 'PENDING'],

  ENUM_CURRENCY_CODE: ['INR', 'USD', 'EUR']   
};
